/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(message_prod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(dd8e18962957a25729abfc0bd2e4336c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ft8/message_prod.h>
// pydoc.h is automatically generated in the build directory
#include <message_prod_pydoc.h>

void bind_message_prod(py::module& m)
{

    using message_prod = gr::ft8::message_prod;


    py::class_<message_prod, gr::block, gr::basic_block, std::shared_ptr<message_prod>>(
        m, "message_prod", D(message_prod))

        .def(py::init(&message_prod::make),
             py::arg("message") = "CQ DX VE4ABC EN19",
             D(message_prod, make))


        ;
}
